version: '3'
services:
  app:
    build: .


  db:
    build: db/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33060:3306"
